### ISSUE TITLE
Conflict to publish on MELPA

### ISSUE THREAD

**Issue by zoedsoupe** [getomni/emacs#1]
**What would you like to be added**:

Relicense this repository with a GPL compatible license.

**Why is this needed**:

To publish on MELPA, they need a GPL compatible license! The MIT license is sometimes ambigous, according to https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses
on the `Expat License` part.

**Is your enhancement request related to a problem? Please describe.**

So, if can't relicense this repository we'll be blocked to publish the package on MELPA.

**Additional context**

Actual PR to add `emacs-omni` to MELPA -> https://github.com/melpa/melpa/pull/7447

There are some minor compilation and lint errors which I'll some trough this week (:

**Comment by zoedsoupe** [comment]
@jpedroschmitz could take a look here?

**Comment by jpedroschmitz** [comment]
Hey @Mdsp9070, I think we can update the license to publish the theme on MELPA.

We could add a GPL-3.0 license. What do you think?

**Comment by zoedsoupe** [comment]
Ok, I'll make the changes and fix compilation issues!
